name: Assets

on:
    push:
        branches:
            - master

jobs:
    deploy-assets:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v3
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: |
                      r2 object put wharfkit/chain/eos.png -f assets/chain/eos.png
